"""
Django settings for Spardha project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import django_heroku
import pyAesCrypt
from pathlib import Path
from decouple import config
import logging
import requests
import json
import traceback

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = int(config("DEBUG", "1"))

if DEBUG:
    SECRET_KEY = "django-insecure-86qk#fplrgzvaj&o0nhbgf@^tx)gcg7+9d7#f#%hwsim1p+3ez"
else:
    SECRET_KEY = config("SECRET_KEY")

ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    "Authentication",
    "Teams",
    "Manager",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_yasg",
    "corsheaders",
    'django.contrib.sites',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
}

ROOT_URLCONF = "Spardha.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "Authentication.UserAccount"
AUTHENTICATION_BACKENDS = ["Authentication.backends.AuthBackend"]
WSGI_APPLICATION = "Spardha.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': config("DB_ENGINE"),
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': config("DB_HOST"),
        'PORT': config("DB_PORT")
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

with open(os.path.join(BASE_DIR, "client_secret.json.aes"), "rb") as encrypted_file:
    with open(os.path.join(BASE_DIR, "client_secret.json"), "wb") as decrypted_file:
        encFileSize = os.stat(os.path.join(BASE_DIR, "client_secret.json.aes")).st_size
        # decrypt file stream
        pyAesCrypt.decryptStream(
            encrypted_file,
            decrypted_file,
            config('SERVICE_ACCOUNT_DECRYPT_KEY'),
            64*1024,
            encFileSize
        )

EMAIL_USE_TLS = True
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
DEFAULT_FROM_EMAIL = config("EMAIL_HOST_USER")
SENDGRID_VERIFY_ACCOUNT_TEMP_ID = config("SENDGRID_VERIFY_ACCOUNT_TEMP_ID")
SENDGRID_API_KEY = config("SENDGRID_API_KEY")
EMAIL_HOST_USER= config("EMAIL_HOST_USER")
EMAIL_HOST_USER_NAME = config("EMAIL_HOST_USER_NAME")
SENDGRID_RESET_ACCOUNT_TEMP_ID = config("SENDGRID_RESET_ACCOUNT_TEMP_ID")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
BASE_URL_FRONTEND = config("BASE_URL_FRONTEND")
CURRENT_URL_BACKEND = config("CURRENT_URL_BACKEND")

# Setup support for proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Activate Django-Heroku.
django_heroku.settings(locals())

DISCORD_URL = config("DISCORD_URL")
DISCORD_WEBHOOK_ID =config("DISCORD_WEBHOOK_ID")
DISCORD_WEBHOOK_TOKEN =config("DISCORD_WEBHOOK_TOKEN")
DISCORD_SHOULD_WAIT_FOR_RESPONSE = config("DISCORD_SHOULD_WAIT_FOR_RESPONSE")

class DiscordWebhookHandler(logging.Handler):
    def __init__(self, webhook_url):
        super().__init__()
        self.webhook_url = webhook_url


    def emit(self, record):
        log_entry = self.format(record)
        data = {'content': log_entry}
        headers = {'Content-Type': 'application/json'}
        response = requests.post(self.webhook_url, data=json.dumps(data), headers=headers)
        if response.status_code != 204:
            print("Failed to send log to Discord webhook.")

discord_webhook_url = DISCORD_URL + DISCORD_WEBHOOK_ID + "/" + DISCORD_WEBHOOK_TOKEN + "?wait=" + DISCORD_SHOULD_WAIT_FOR_RESPONSE
logger = logging.getLogger('django')

logger.setLevel(logging.ERROR) 

discord_handler = DiscordWebhookHandler(webhook_url=discord_webhook_url)
logger.addHandler(discord_handler)

try:
    from django.core.management import execute_from_command_line
    execute_from_command_line(['manage.py', 'runserver']) 
except Exception as e:
    error_message = f"An error occurred: {str(e)}\n\n{traceback.format_exc()}"
    try:
        logger.error(error_message)
        discord_handler.emit(logging.makeLogRecord({'msg': error_message}))  # Manually emit the error message to Discord
    except Exception as send_error:
        logger.error("Error in sending errors to Discord: " + str(send_error))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'discord_webhook': {
            'level': 'ERROR', 
            'class': 'your_module_name.DiscordWebhookHandler', 
            'webhook_url': discord_webhook_url,
 },
    },
    'loggers': {
        'django': {
            'handlers': ['discord_webhook'], 
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
